// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
 
#include QMK_KEYBOARD_H

#define QWERTY 0 // Base qwerty


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [QWERTY] = LAYOUT(
      KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8,
      KC_INSERT, KC_HOME, KC_PAGE_UP, KC_F12, KC_DELETE, KC_END, KC_PAGE_DOWN, KC_KP_PLUS,
      LCTL(KC_O), LCTL(KC_M), LCTL(KC_D), LCTL(KC_S), LCTL(KC_E), LCTL(KC_F), LCTL(KC_N), LCTL(KC_G), LCTL(KC_X), LCTL(KC_A),
      LCTL(KC_U), LCTL(KC_C), LCTL(KC_L), LCTL(KC_H), LCTL(KC_Z), LCTL(KC_P), LCTL(KC_Q), LCTL(KC_W), LCTL(KC_J), LCTL(KC_B),
      LALT(KC_P), LALT(KC_N), LALT(KC_U), LALT(KC_L), LALT(KC_COMMA), LALT(KC_DOT), LALT(KC_X), LALT(KC_M),
      LALT(KC_S), LALT(KC_F), LALT(KC_D), LALT(KC_R), LALT(KC_K), LALT(KC_Z), LALT(KC_I),
      LALT(KC_H), 
      LALT(KC_LEFT_BRACKET), KC_7, KC_8, KC_9, LALT(KC_EQUAL), LALT(KC_O), LALT(KC_E),
      LALT(KC_RIGHT_BRACKET), KC_4, KC_5, KC_6, LALT(KC_T), LALT(KC_B),
      KC_KP_ASTERISK, KC_1, KC_2, KC_3, KC_MINUS, LALT(KC_W),
      LALT(KC_QUOTE), KC_LEFT_BRACKET, KC_0, LCTL(KC_DOT), LALT(KC_8), LALT(KC_2), LALT(KC_C), LALT(KC_V),
      LALT(KC_SEMICOLON), KC_RIGHT_BRACKET, KC_LEFT_SHIFT, LCTL(KC_SLASH), LALT(KC_Q), KC_ENTER, LALT(KC_BACKSPACE), LALT(KC_Y),
      KC_ESC, KC_SPACE, KC_TAB, KC_GRAVE, KC_LEFT, KC_RIGHT, KC_UP, KC_DOWN, KC_BACKSLASH, KC_CAPS_LOCK,
      KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P,
      KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SEMICOLON,
      KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH

  )

};

